# Generated by Django 3.0.2 on 2020-06-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name': 'Remédio - Dados', 'verbose_name_plural': 'Remédios - Dados'},
        ),
        migrations.AlterModelTable(
            name='medicines',
            table='sis_medicine',
        ),
    ]
