# Generated by Django 3.0.2 on 2020-06-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200610_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Produto - Tipo',
                'verbose_name_plural': 'Produto - Tipos',
                'db_table': 'sis_product_type',
            },
        ),
        migrations.AddField(
            model_name='medicines',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ProductType'),
        ),
    ]
