# Generated by Django 3.0.2 on 2020-06-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200616_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Pedido - Dados',
                'verbose_name_plural': 'Pedido - Dados',
                'db_table': 'sis_order',
            },
        ),
    ]
